### ISSUE TITLE
SWCAN pins aren't initialized

### ISSUE THREAD

**Issue by Mike4U** [collin80/GVRET#7]
When starting up GVRET, output pins SWCANMode0 and SWCANMode1 aren't initialized.  They were floating around 1.5 volts until CAN1 is turned on or off.

**Comment by collin80** [comment]
Yup, that's a valid concern. They should be initialized to a set state upon start up. I believe that LOW for both pins would be appropriate.

**Comment by Mike4U** [comment]
Forgot to mention that SWCANMode0 is a confusing pin name shouldn't it be SWCANMode0PIN

**Comment by collin80** [comment]
Ok, all of this is fixed in a commit I haven't posted yet to GIT but will be soon. The settings have been renamed to have Pin after them and the two pins are now initialized as outputs and they are immediately set appropriately. If you asked for single wire mode on boot then it will immediately be selected. Otherwise the single wire mode pins will both be set low immediately.
